-- Migration: Subscription System
-- Creates tables for managing premium subscriptions with activation codes

-- Activation codes generated by admin
CREATE TABLE IF NOT EXISTS activation_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(12) UNIQUE NOT NULL,
    plan_type VARCHAR(20) DEFAULT 'monthly', -- monthly, yearly
    duration_days INTEGER DEFAULT 30,
    expires_at TIMESTAMPTZ, -- Code expiration (can be null for never-expiring codes)
    redeemed_at TIMESTAMPTZ,
    redeemed_by UUID REFERENCES auth.users(id),
    payment_reference TEXT, -- Reference to payment (email/transfer)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- User subscription status
CREATE TABLE IF NOT EXISTS user_subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) UNIQUE NOT NULL,
    plan_type VARCHAR(20) DEFAULT 'free', -- free, premium
    is_premium BOOLEAN DEFAULT false,
    premium_until TIMESTAMPTZ,
    activated_via UUID REFERENCES activation_codes(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE activation_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_subscriptions ENABLE ROW LEVEL SECURITY;

-- Policies for activation_codes
-- Users can only view codes that they have redeemed
CREATE POLICY "Users can view their redeemed codes"
    ON activation_codes FOR SELECT
    USING (redeemed_by = auth.uid());

-- Policies for user_subscriptions
-- Users can view their own subscription
CREATE POLICY "Users can view own subscription"
    ON user_subscriptions FOR SELECT
    USING (user_id = auth.uid());

-- Users can insert their own subscription (only if none exists)
CREATE POLICY "Users can create own subscription"
    ON user_subscriptions FOR INSERT
    WITH CHECK (user_id = auth.uid());

-- Users can update their own subscription
CREATE POLICY "Users can update own subscription"
    ON user_subscriptions FOR UPDATE
    USING (user_id = auth.uid());

-- Function to redeem activation code
CREATE OR REPLACE FUNCTION redeem_activation_code(code_input VARCHAR)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_code activation_codes%ROWTYPE;
    v_user_id UUID;
    v_premium_until TIMESTAMPTZ;
BEGIN
    v_user_id := auth.uid();
    
    -- Find the code
    SELECT * INTO v_code 
    FROM activation_codes 
    WHERE code = UPPER(code_input)
    AND redeemed_at IS NULL
    AND (expires_at IS NULL OR expires_at > now());
    
    IF NOT FOUND THEN
        RETURN json_build_object('success', false, 'error', 'Código inválido o ya utilizado');
    END IF;
    
    -- Calculate premium duration
    v_premium_until := now() + (v_code.duration_days || ' days')::INTERVAL;
    
    -- Mark code as redeemed
    UPDATE activation_codes 
    SET redeemed_at = now(), redeemed_by = v_user_id
    WHERE id = v_code.id;
    
    -- Update or create subscription
    INSERT INTO user_subscriptions (user_id, plan_type, is_premium, premium_until, activated_via)
    VALUES (v_user_id, v_code.plan_type, true, v_premium_until, v_code.id)
    ON CONFLICT (user_id) 
    DO UPDATE SET 
        plan_type = v_code.plan_type,
        is_premium = true,
        premium_until = GREATEST(user_subscriptions.premium_until, v_premium_until),
        activated_via = v_code.id,
        updated_at = now();
    
    RETURN json_build_object(
        'success', true, 
        'premium_until', v_premium_until,
        'plan_type', v_code.plan_type
    );
END;
$$;

-- Function to check premium status
CREATE OR REPLACE FUNCTION check_premium_status()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_sub user_subscriptions%ROWTYPE;
BEGIN
    SELECT * INTO v_sub 
    FROM user_subscriptions 
    WHERE user_id = auth.uid();
    
    IF NOT FOUND THEN
        RETURN json_build_object('is_premium', false, 'plan_type', 'free');
    END IF;
    
    -- Check if still premium
    IF v_sub.is_premium AND v_sub.premium_until > now() THEN
        RETURN json_build_object(
            'is_premium', true, 
            'plan_type', v_sub.plan_type,
            'premium_until', v_sub.premium_until
        );
    ELSE
        -- Premium expired, update status
        UPDATE user_subscriptions 
        SET is_premium = false, plan_type = 'free', updated_at = now()
        WHERE user_id = auth.uid();
        
        RETURN json_build_object('is_premium', false, 'plan_type', 'free');
    END IF;
END;
$$;
